name: Telegram News Bot

on:
  schedule:
    # exemplo: rodar 08:00 e 18:00 America/Sao_Paulo (UTC-3) -> em UTC = 11:00 e 21:00
    - cron: '0 11 * * *'
    - cron: '0 21 * * *'
  workflow_dispatch: {}

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run bot
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID:  ${{ secrets.CHAT_ID }}
          NEWS_API_KEY: ${{ secrets.NEWS_API_KEY }}
          COUNTRY: br
          MAX_ARTICLES: 5
        run: python bot.py
