name: Telegram News Bot

on:
  schedule:
    - cron: "0 12 * * *"   # executa todo dia às 12:00 UTC (09:00 no Brasil)
  workflow_dispatch:        # permite rodar manualmente

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run bot
        run: python bot.py
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          NEWSAPI_KEY: ${{ secrets.NEWSAPI_KEY }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
